
# name: Sample Github CD for Bizfly App Engine

# on:
#   push:
#     branches: [ "master" ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Trigger deploy in Bizfly App Engine
#         run: curl -X POST ${{ secrets.WEBHOOK_URL }}

